### ISSUE TITLE
Refactor: Destructure Props

### ISSUE THREAD

**Issue by ash1eygrace** [ash1eygrace/ai-content#24]
Once [Refactor: Migrate from Class Components to Functional Components](https://github.com/ash1eygrace/ai-content/issues/22) #22  is complete, we'll want to refactor our functional components to destructure props to simplify the codebase and reduce repetition.

The main goals of this refactor are to:

- Improve the readability and maintainability of our codebase.
- Simplify the passing of props to components.
- Reduce the amount of repetition in our codebase.
- Take advantage of destructuring to improve performance.

To achieve these goals, we will need to perform the following tasks:

- Identify components that still need to be destructured.
- Refactor these components to destructure props.
- Test the updated code to ensure that the application still works as expected.

**Comment by Mr-G-D** [comment]
Permission to proceed on this task

**Comment by ash1eygrace** [comment]
Hey, sorry I'm going to be working on these as part of practice for some courses I've done. Thank you for offering your time! This is just my personal project where I learn so I'd like to take care of the rest myself. Thanks.

**Comment by ash1eygrace** [comment]
Hey @Mr-G-D , sorry I'm going to be working on these as part of practice for some courses I've done. Thank you for offering your time! This is just my personal project where I learn so I'd like to take care of the rest myself. Thanks.
