### ISSUE TITLE
Wrap GeneratorComponent Card.Text in <p> and Assign a Class for Improved Styling

### ISSUE THREAD

**Issue by ash1eygrace** [ash1eygrace/ai-content#49]
**Problem** 
Currently, the `GeneratorComponent` `Card.Text` is not wrapped in a `<p>` element, which makes it difficult to apply consistent styles and spacing to the text content.

**Proposed Solution** 
To enable better styling and maintain consistency in the appearance of the `Card.Text` content, let's wrap it in a `<p>` element and assign a class to it. This will make it easier to manage styles and improve the overall look of the component.

**Implementation Steps**
1.  Update the `GeneratorComponent` to wrap the `Card.Text` content in a `<p>` element.
2.  Assign a class to the `<p>` element (e.g., `card-text-content`), allowing for easier styling and customization.
3.  For now only add styles to test the CSS but let's not commit any style changes. Those will be handled in #47 
4.  Test the updated component in various scenarios to ensure that the new styles are applied correctly and maintain a consistent appearance.

**Comment by Mr-G-D** [comment]
Hi,
I am willing to work on this task. Let me know if I can proceed.

**Comment by ash1eygrace** [comment]
Hey @Mr-G-D thanks for helping out!  

Please tag me for review when you're done :)

**Comment by ash1eygrace** [comment]
The way you have it now with the p nested in the CardText component is great and consistent with the response in the card text on lines 72-74. For now, let's not add a className, since the `<p>` tag alone will be sufficient for the styles that will be added in #47.

**Comment by ash1eygrace** [comment]
Actually, It looks like React Bootstrap's Card.Text in the DOM is actually looks like this:

```
<p class="card-text">The Response from the AI for your Product Description will show here.</p>
```

That said, this is a non-issue, and it can be closed.
