### ISSUE TITLE
Fix TL;DR generator link in GeneratorList object

### ISSUE THREAD

**Issue by ash1eygrace** [ash1eygrace/ai-content#51]
### Issue

Currently, the TL;DR object in `data/GeneratorList` has the link `li-job-description`, but the correct link is the route `path="/tldr"`. This is causing a blank page when navigating to Generators and clicking on the TL;DR generator.

### Steps to Reproduce

1. Navigate to the Generators page
2. Click on the TL;DR generator

### Expected Behavior

The TL;DR generator should load properly when clicked, navigating to the correct route.

**Comment by Mr-G-D** [comment]
Hi @ash1eygrace ,
I am willing to work on this task, Let mw know if I can proceed.

**Comment by ash1eygrace** [comment]
@Mr-G-D, thanks again for volunteering. I've invited you. Please request a review from me when you're ready! :)
